name: insta_chat

description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.12.1
  conditional_builder_null_safety: ^0.0.6
  connectivity_plus: ^5.0.1
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  firebase_auth: ^4.12.0
  firebase_core: ^2.20.0
  firebase_messaging: ^14.7.2
  firebase_storage: ^11.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_local_notifications: ^16.1.0
  flutter_phone_direct_caller: ^2.1.1
  flutter_svg: ^2.0.8
  fluttertoast: ^8.2.2
  full_screen_image_null_safe: ^2.0.0
  google_fonts: ^6.1.0
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  modal_progress_hud_nsn: ^0.4.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  url_launcher: ^6.2.1
  uuid: ^4.1.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

flutter_assets:
  assets_path: assets/images/
  output_path: lib/
  filename: image_assets.dart
  field_prefix: null
