// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3arISy0y_sFUR3mn2U2ugY5BYXCuVDJE',
    appId: '1:688748987324:web:7c91e910de433908e1e1b9',
    messagingSenderId: '688748987324',
    projectId: 'insta-chat-e6467',
    authDomain: 'insta-chat-e6467.firebaseapp.com',
    storageBucket: 'insta-chat-e6467.appspot.com',
    measurementId: 'G-G4X1CZL0G9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnqfwQHEhvNopg08wRRl6LQL8ibrXdgAE',
    appId: '1:688748987324:android:5829c59f3cc1f59ee1e1b9',
    messagingSenderId: '688748987324',
    projectId: 'insta-chat-e6467',
    storageBucket: 'insta-chat-e6467.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwuzNxJX_HmR6-iyUmMqQDcPDzlQT9vGY',
    appId: '1:688748987324:ios:ee7101d38207bb23e1e1b9',
    messagingSenderId: '688748987324',
    projectId: 'insta-chat-e6467',
    storageBucket: 'insta-chat-e6467.appspot.com',
    iosBundleId: 'com.example.instaChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwuzNxJX_HmR6-iyUmMqQDcPDzlQT9vGY',
    appId: '1:688748987324:ios:46735f365dfe9d1be1e1b9',
    messagingSenderId: '688748987324',
    projectId: 'insta-chat-e6467',
    storageBucket: 'insta-chat-e6467.appspot.com',
    iosBundleId: 'com.example.instaChat.RunnerTests',
  );
}
